version: '3'
services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: ./server/Dockerfile
    volumes:
      - type: bind
        source: ./
        target: /src
    tty: true
    ports:
      - 9090:8000
  # proxy:
  #   build:
  #     context: ./proxy
  #     dockerfile: Dockerfile
  #   container_name: storage
  #   environment:
  #     - ENVOY_UID=1000
  #     - ENVOY_GID=1000
  #   ports:
  #     - 443:443