version: '3'
services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: ./server/Dockerfile
    volumes:
      - type: bind
        source: ./
        target: /usr/src/app
    command: "go run ./server/main.go"
    tty: true
    ports:
      - 8000:8000
    networks:
      - backend
  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    container_name: proxy
    ports:
      - 9901:9901
      - 9000:9000
    networks:
      - backend
networks:
  backend:
    driver: bridge